# This file provides utility for prompting non-thinking models (e.g. Llama 3) to think
# before responding. 
import random

def add_thinking_prompt(content: str, random_cot: bool = True) -> str:
    if random_cot:
        cot_instruction = random.choice(COT_INSTRUCTIONS)
    else:
        cot_instruction = DEFAULT_COT
    return f"{content}\n\n{cot_instruction}"

MODEL_TO_THINKING_OVERRIDES = {
    "qwen/qwen3-0.6b": lambda enable_thinking: dict(enable_thinking=enable_thinking),
    "qwen/qwen3-1.7b": lambda enable_thinking: dict(enable_thinking=enable_thinking),
    "qwen/qwen3-4b": lambda enable_thinking: dict(enable_thinking=enable_thinking),
    "qwen/qwen3-8b": lambda enable_thinking: dict(enable_thinking=enable_thinking),
}

DEFAULT_COT = "Think before responding. Put your chain of thought/scratchpad between the <think> and </think> tags before providing your final response."

COT_INSTRUCTIONS = [
    DEFAULT_COT,
    "If helpful, you can think before responding. Put your thinking between <thinking> and </thinking> tags. Then, provide your final response between <response> and </response> tags.",
    "Respond in the following format: <thinking>...</thinking> <response>...</response>",
    "Explain your reasoning before providing your final response.",
    "Explain your reasonining between <reasoning> and </reasoning> tags.",
    "Provide your final answer within <answer>...</answer> tags. Optionally, you can explain your reasoning between <reasoning> and </reasoning> tags.",
    "You may include your reasoning before answering. Use <reasoning>...</reasoning> to enclose your thoughts, and <final>...</final> for your answer.",
    "First, think through the problem and enclose your thoughts in <thought>...</thought>. Then, present your answer clearly in <output>...</output>.",
    "Use <step-by-step>...</step-by-step> for your intermediate reasoning, followed by <answer>...</answer> for the final result.",
    "Start with your analysis in <deliberation>...</deliberation>. Conclude with a clear answer in <response>...</response>.",
    "You may show your chain of thought in <chain>...</chain> and state your final decision in <decision>...</decision>.",
    "Wrap your reasoning process in <logic>...</logic>, and your ultimate conclusion in <conclusion>...</conclusion>.",
    "Think carefully before answering. Put your process in <process>...</process> and your solution in <solution>...</solution>.",
    "Please provide your thought process first, enclosed in <rationale>...</rationale>, and then give your final answer in <final_answer>...</final_answer>.",
    "Include your reasoning in <analysis>...</analysis> and your conclusion in <result>...</result>.",
    "Begin with <thinking_process>...</thinking_process> to show how you reasoned through the problem. Finish with <response>...</response>.",
    "Use <explanation>...</explanation> to walk through the logic. Then state your answer in <output>...</output>.",
    "Present your logical steps in <reasoning_chain>...</reasoning_chain> and conclude with <final_response>...</final_response>.",
    "Start with <evaluation>...</evaluation> to explain how you analyzed the question. Then, give your answer in <decision>...</decision>.",
    "Outline your reasoning in <deduction>...</deduction> and present the final answer in <resolution>...</resolution>.",
    "First explain in <justification>...</justification>, then give your definitive answer in <answer>...</answer>.",
    "Place your step-by-step logic in <path>...</path> and your outcome in <solution>...</solution>.",
    "Break down the problem in <walkthrough>...</walkthrough> before stating your answer in <conclusion>...</conclusion>.",
    "Reason through the problem in <examine>...</examine> and finalize with <respond>...</respond>.",
    "Give your thought process inside <trace>...</trace> and the answer inside <reply>...</reply>.",
    "Write your full reasoning under <work>...</work>, then state the answer clearly in <end>...</end>.",
    "Use <rundown>...</rundown> to explain your steps, and <final>...</final> to share your answer.",
    "First, walk through your reasoning process step by step. Then, clearly state your final answer.",
    "Begin by explaining how you approach the problem. Afterward, give your final response.",
    "Start with a detailed breakdown of your thought process. Conclude with a concise answer.",
    "Explain your logic as you work through the problem. When you're done, provide your conclusion.",
    "Think out loud as you reason through the question. End with a definitive answer.",
    "Work through the problem in detail, reasoning carefully. Then summarize your final decision.",
    "Describe each step you take to solve the problem. Finish by stating the final result.",
    "Provide a thorough explanation of how you arrive at your answer. Then state the answer clearly.",
    "Show your reasoning process from start to finish. Make sure to give your final answer at the end.",
    "Break the problem into logical steps and explain each one. Then give your final response.",
    "Write out your reasoning clearly and methodically. Conclude with your final conclusion.",
    "Reflect on the problem and describe your full reasoning. Then, say what your answer is.",
    "Think critically about the question and narrate your process. Then provide your final decision.",
    "Show your internal reasoning inside `{{Rationale}}...{{/Rationale}}`. Give the final conclusion inside `{{Conclusion}}...{{/Conclusion}}`.",
    "Detail your problem-solving steps between `[Steps]...[/Steps]`. Provide the answer between `[Result]...[/Result]`.",
    "Explain the derivation process using `Derivation: ... End Derivation`. State the final output using `Output: ... End Output`.",
    "Map out your thought path within `<Path>...</Path>`. State the final destination within `<Destination>...</Destination>`.",
    "Provide your analysis enclosed in `<<Analysis>>...<</Analysis>>`. Present the determined answer enclosed in `<<Answer>>...<</Answer>>`.",
    "Elaborate on your thinking process with `// Elaboration Start` and `// Elaboration End`. Provide the final response with `// Response Start` and `// Response End`.",
    "Use `(Thought Process: ... )` to show your thinking. Use `(Final Answer: ... )` for the result.",
    "Lay out the groundwork in `<Foundation>...</Foundation>`. Build the final answer in `<Structure>...</Structure>`.",
    "Document the logical flow in `{* Logic Flow *} ... {* /Logic Flow *}`. Deliver the outcome in `{* Outcome *} ... {* /Outcome *}`.",
    "Begin with your deliberation, marked by `Deliberation: ...`. Conclude with your final decision, marked by `Decision: ...`.",
    "Record your internal monologue in `<Monologue>...</Monologue>`. State the external response in `<Statement>...</Statement>`.",
    "Chart the sequence of reasoning within `[[Sequence]]...[[/Sequence]]`. Present the end point within `[[Endpoint]]...[[/Endpoint]]`.",
    "Dissect the problem in `<Dissection>...</Dissection>`. Synthesize the answer in `<Synthesis>...</Synthesis>`.",
    "Narrate your thought process using `Narrative: ...`. Provide the concluding answer using `Conclusion: ...`.",
    "Outline your strategy in `<Strategy>...</Strategy>`. Execute the final answer in `<Execution>...</Execution>`.",
    "Feel free to think it through out loud first, then just drop your answer at the end.",
    "Walk yourself through the problem—no rush. Once you're set, say what you'd go with.",
    "You can talk it out step by step. Just wrap up with whatever you think the answer is.",
    "Think it through however you like, and then let me know your final call.",
    "Start by working through the logic in your own way. When you're done, give the answer.",
    "Lay out your thinking as it comes to you. At the end, just say what you'd choose.",
    "Break it down how you want, no pressure. Then tell me what your final answer would be.",
    "Talk yourself through the reasoning part. When it feels right, give your answer.",
    "Explain it like you're figuring it out in real time, then land on your pick.",
    "Take a moment to think it through, and when you're ready, just say your answer.",
    "Work it out however makes sense to you. Then drop your answer when you're good.",
    "Go step by step, like you're thinking out loud. End with whatever answer you'd settle on.",
    "Walk through your reasoning step by step, and once it all clicks, share your answer.",
    "Take me through your thought process from start to finish, then tell me your conclusion.",
    "Think out loud as you piece it together. When you’re ready, just state your answer.",
    "Break down the problem in your own words, then wrap up with your choice.",
    "Talk through each part as you solve it, and then give your final answer.",
    "Map out your logic as you go, and once you’re confident, give your answer.",
    "Reason it out at your own pace, and when you’re set, let me know your answer.",
    "Feel free to puzzle it out stepwise. At the end, just say your final pick.",
    "Process the question however you like. Once you’ve worked it out, share your answer.",
    "Unpack the problem in detail, and when you’re ready, provide your answer.",
    "Work through the details in your own style, and then land on your answer.",
    "Think through the scenario, explaining as you go, and finish with your answer.",
    "Go through your reasoning openly, and then make your final call.",
    "Lay out your analysis clearly, and when you reach a conclusion, share it.",
    "Step through your logic in real time, and end with your decision.",
    "Explain your approach as you solve it, then just give your answer at the end.",
    "Go through the motions of solving it, and when you’re done, state your answer.",
    "Work the problem out in your own way, and when you’re ready, say your answer.",
    "Detail your thought process as it unfolds, then close with your answer.",
    "Take your time to reason through it, and when you’ve got it, give your answer.",
    "Unpack your reasoning in <logic>...</logic>. Conclude with your solution in <result>...</result>.",
    "Share your thought process inside [Reasoning]...[/Reasoning]. State your answer in [Answer]...[/Answer].",
    "Walk through your approach in <<<Thinking>>>...<<<End Thinking>>>. Provide your answer in <<<Answer>>>...<<<End Answer>>>.",
    "Place your analysis in <Breakdown>...</Breakdown>. Offer the answer in <Solution>...</Solution>.",
    "Use [[Rationale]]...[[/Rationale]] for your reasoning. Use [[Conclusion]]...[[/Conclusion]] for your answer.",
    "Think through the problem in # Reasoning: ... # End Reasoning. Give your answer in # Answer: ... # End Answer.",
    "Lay out your process in <Process>...</Process>. Deliver your conclusion in <Conclusion>...</Conclusion>.",
    "Step through your logic in {Reasoning: ... }. Present your answer in {Answer: ... }.",
    "Present your thought process in --- Reasoning --- ... --- End Reasoning ---. State your answer in --- Answer --- ... --- End Answer ---.",
    "Outline your thinking in (Reasoning Start)...(Reasoning End). Wrap up with (Answer Start)...(Answer End).",
    "Describe your approach using <Approach>...</Approach>. Summarize your answer using <Summary>...</Summary>.",
    "Go through your logic in [Logic Path]...[/Logic Path]. Finalize with [Final Response]...[/Final Response].",
    "Map out your steps in <<Steps>>...<</Steps>>. Place your answer in <<Result>>...<</Result>>.",
    "Narrate your reasoning in <Explanation>...</Explanation>. State your answer in <Reply>...</Reply>.",
    "Explain your process inside {Process: ...}. Conclude with {Result: ...}.",
    "Break down your logic in [Analysis]...[/Analysis]. Conclude with your answer in [Conclusion]...[/Conclusion].",
    "Think out your process in <Thoughts>...</Thoughts>. Share your answer in <Answer>...</Answer>.",
    "Detail your reasoning in [[Analysis]]...[[/Analysis]]. Give the answer in [[Final]]...[[/Final]].",
    "Work through your thoughts in --- Process --- ... --- /Process ---. Finish with --- Solution --- ... --- /Solution ---.",
    "Talk through your logic in {Deliberation}...{/Deliberation}. Give your answer in {Decision}...{/Decision}.",
]